- assert:
    that:
      - 'happn-cluster_version != ""'

- name: install apt packages
  apt: "name='{{ item }}' state=present"
  with_items:
    - git
    - python-pip

- name: install docker-py
  pip: name=docker-py version=0.3.1

- name: create build directory
  file: >
    dest="{{ happn-cluster_build_dir }}"
    state=directory

- name: clone happn-cluster git repo
  git: >
    repo="{{ happn-cluster_repo }}"
    dest="{{ happn-cluster_build_dir }}/happn-cluster"
    version="v{{ happn-cluster_version }}"
  register: happn-cluster_repo

- name: remove git deploy key
  file: dest=/tmp/github_deploy_key state=absent

- name: archive repo
  shell: >
    cd "{{ happn-cluster_build_dir }}/{{ item }}" &&
    git archive -o ../{{ item }}.tar HEAD
  with_items:
    - happn-cluster

- name: generate templates
  template: >
    src="{{ item.src }}"
    dest="{{ happn-cluster_build_dir }}/{{ item.dest }}"
  with_items:
    - { src: "Dockerfile", dest: "Dockerfile" }
    #- { src: "runapp.sh", dest: "runapp.sh" }

- name: build image
  docker_image: >
    name="{{ happn-cluster_image_name }}"
    tag="{{ happn-cluster_image_tag }}"
    path="{{ happn-cluster_build_dir }}"
    state=build

- name: tag
  command: >
    docker tag -f
    {{ happn-cluster_image_name }}:{{ happn-cluster_image_tag }}
    {{ happn-cluster_image_name }}:{{ happn-cluster_extra_tag }}
when: happn-cluster_extra_tag != ''
